// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuB1ncLPxhIAUT09hKjNbNOnWHOUdqgeY',
    appId: '1:891168595577:web:80ad98caaa6d35a343fea8',
    messagingSenderId: '891168595577',
    projectId: 'wni-db-215e3',
    authDomain: 'wni-db-215e3.firebaseapp.com',
    databaseURL: 'https://wni-db-215e3-default-rtdb.firebaseio.com',
    storageBucket: 'wni-db-215e3.appspot.com',
    measurementId: 'G-B4R0PN7Y0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEcGWMTw_JDDVCmehE1bt1gyr9aB4pXgk',
    appId: '1:891168595577:android:b492fc8fc331d61a43fea8',
    messagingSenderId: '891168595577',
    projectId: 'wni-db-215e3',
    databaseURL: 'https://wni-db-215e3-default-rtdb.firebaseio.com',
    storageBucket: 'wni-db-215e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeW6DhTVKDSnU0kJZXiPmDVPe8T6yuMnY',
    appId: '1:891168595577:ios:61a59abc6866c41d43fea8',
    messagingSenderId: '891168595577',
    projectId: 'wni-db-215e3',
    databaseURL: 'https://wni-db-215e3-default-rtdb.firebaseio.com',
    storageBucket: 'wni-db-215e3.appspot.com',
    iosClientId: '891168595577-s0qcbmcu0ecpenb1pu5lcgjvo6hc3cn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.projestuaspab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeW6DhTVKDSnU0kJZXiPmDVPe8T6yuMnY',
    appId: '1:891168595577:ios:61a59abc6866c41d43fea8',
    messagingSenderId: '891168595577',
    projectId: 'wni-db-215e3',
    databaseURL: 'https://wni-db-215e3-default-rtdb.firebaseio.com',
    storageBucket: 'wni-db-215e3.appspot.com',
    iosClientId: '891168595577-s0qcbmcu0ecpenb1pu5lcgjvo6hc3cn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.projestuaspab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuB1ncLPxhIAUT09hKjNbNOnWHOUdqgeY',
    appId: '1:891168595577:web:a7e4d73ccca51f6543fea8',
    messagingSenderId: '891168595577',
    projectId: 'wni-db-215e3',
    authDomain: 'wni-db-215e3.firebaseapp.com',
    databaseURL: 'https://wni-db-215e3-default-rtdb.firebaseio.com',
    storageBucket: 'wni-db-215e3.appspot.com',
    measurementId: 'G-ZSQQ5TFLMS',
  );

}